### ISSUE TITLE
error when start up

### ISSUE THREAD

**Issue by WhiteSeasons** [bcgov/issuer-kit#338] opened 2022-02-07 07:49 UTC
./manage start

the log show error when init agent, as follows:

agent_1             | 2022-02-07 07:20:34,078 aries_cloudagent.admin.server ERROR Handler error with exception: Credential definition GSqQTPcQVdLtBYYSgBJXai:3:CL:8:issuer-kit-demo is on ledger default but not in wallet issuer_kit_agent
agent_1             | Traceback (most recent call last):
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/credential_definitions/routes.py", line 209, in credential_definitions_send_credential_definition
agent_1             |     endorser_did=endorser_did,
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 681, in create_and_send_credential_definition
agent_1             |     f"Credential definition {credential_definition_id} is on "
agent_1             | aries_cloudagent.ledger.error.LedgerError: Credential definition GSqQTPcQVdLtBYYSgBJXai:3:CL:8:issuer-kit-demo is on ledger default but not in wallet issuer_kit_agent

so is there any configuration or parameters need to be added ?

**Comment by WadeBarnes** [comment] 2022-02-07 15:24
That error indicates the issuer is trying to generate, what it thinks is, a new credential definition and register it with the ledger and it's wallet, but the transaction already exists on the ledger.  This can happen when you've run `./manage down` or `./manage rm` in issuer-kit and not cleared out the records in `von-network` in a similar manner.  Basically you've lost the wallet containing the records and you need to start fresh.

In these situations you can:
- Clear out `von-network` and start again.  Starting fresh with a clean ledger and wallet.
- Bump the version number of the associated schema.  Which will allow the agent to register new versions of the schema and cref-def.
- Change the identity of the agent by providing a new seed.  Which will allow the agent to register the same versions of the schema and cred-def using a new identity (DID).

**Comment by zhangbobo2023** [comment] 2022-02-08 08:24
@WadeBarnes Thank you for your support，I have clean and then start again，this error is solved when a new one arose，is there a problem with my operation ？


agent_1             | 2022-02-08 06:30:39,912 aries_cloudagent.admin.server ERROR Handler error with exception: Tails file for rev reg GSqQTPcQVdLtBYYSgBJXai:4:GSqQTPcQVdLtBYYSgBJXai:3:CL:8:issuer-kit-demo:CL_ACCUM:171d6e70-d11d-467a-bf3a-3d1fe9214576 failed to upload: Exceeded maximum put attempts
agent_1             |
agent_1             | =================
agent_1             | Traceback (most recent call last):
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 162, in ready_middleware
agent_1             |     return await handler(request)
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in debug_middleware
agent_1             |     return await handler(request)
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
agent_1             |     return await handler(request)
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 290, in check_token
agent_1             |     return await handler(request)
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 366, in setup_context
agent_1             |     return await task
agent_1             |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/credential_definitions/routes.py", line 261, in credential_definitions_send_credential_definition
agent_1             |     f"Tails file for rev reg {registry_record.revoc_reg_id} "
agent_1             | aiohttp.web_exceptions.HTTPInternalServerError: Tails file for rev reg GSqQTPcQVdLtBYYSgBJXai:4:GSqQTPcQVdLtBYYSgBJXai:3:CL:8:issuer-kit-demo:CL_ACCUM:171d6e70-d11d-467a-bf3a-3d1fe9214576 failed to upload: Exceeded maximum put attempts

**Comment by WadeBarnes** [comment] 2022-02-08 14:15
Get the latest and try restarting the project.  I pushed a fix for an issue I found with the `tails-server` build that could have prevented it from starting.  Though the error should have stopped the project from starting at all.

**Comment by zhangbobo2023** [comment] 2022-02-09 02:41
@WadeBarnes 

I have found the situation，then download the tails-server at local，modify the parameter in docker-compose.yml file：

 tails-server:
    build:
      context: /root/indy-tails-server

Now i have got the latest project，but the same error when start ：


agent_1             | 2022-02-09 02:30:56,037 aries_cloudagent.admin.server ERROR Handler error with exception: Tails file for rev reg GSqQTPcQVdLtBYYSgBJXai:4:GSqQTPcQVdLtBYYSgBJXai:3:CL:8:issuer-kit-demo:CL_ACCUM:79593f83-88a8-42cc-b50c-b4a326f869fe failed to upload: Exceeded maximum put attempts

**Comment by zhangbobo2023** [comment] 2022-02-11 07:41
@WadeBarnes Yes，i have tried several times. von-network and issuer-kit are running at the same server:

![1644564819(1)](https://user-images.githubusercontent.com/87514220/153553120-979d31f0-0efc-4897-945d-75f99e83e718.png)

and the tails-server log when running:

![1644564947(1)](https://user-images.githubusercontent.com/87514220/153553333-6ca19dc7-62c2-4fc0-baf2-cf3cc529a62d.png)

Is there a problem with the  TAILS_SERVER_URL parameter configuration ?

**Comment by esune** [comment] 2022-02-11 17:15
> @WadeBarnes
> 
> I have found the situation，then download the tails-server at local，modify the parameter in docker-compose.yml file：
> 
> tails-server: build: context: /root/indy-tails-server
> 
> Now i have got the latest project，but the same error when start ：
> 
> agent_1 | 2022-02-09 02:30:56,037 aries_cloudagent.admin.server ERROR Handler error with exception: Tails file for rev reg GSqQTPcQVdLtBYYSgBJXai:4:GSqQTPcQVdLtBYYSgBJXai:3:CL:8:issuer-kit-demo:CL_ACCUM:79593f83-88a8-42cc-b50c-b4a326f869fe failed to upload: Exceeded maximum put attempts

This change to `docker-compose` is unnecessary. I cloned both `von-network` and `issuer-kit` and started from scratch and could not reproduce your issue.

Please make sure you have the latest code and run in both projects:
- `./manage rm` to clean-up old stuff
- `./manage build` to build the new images
- `./manage start`

**Comment by zhangbobo2023** [comment] 2022-02-18 09:48
@WadeBarnes @esune 

Thank you for your support。I have deleted all images while cloned latest code，now running well。

But i have a new question， the service exposed on http://47.108.93.62:8180/auth/ can operate well，while http://47.108.93.62:8081 and http://47.108.93.62:8082 can not show。

from the log terminal， it seems accept the request， but no response：

issuer-admin_1      | {"level":"info","ts":1645176088.6578786,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"183.129.165.194:45950","proto":"HTTP/1.1","method":"GET","host":"47.108.93.62:8081","uri":"/","headers":{"Cookie":["io=IRzsWE1QPM3_bhCGAAAA"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"],"Purpose":["prefetch"],"Accept-Encoding":["gzip, deflate"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Language":["zh-CN,zh;q=0.9"],"Connection":["keep-alive"],"Upgrade-Insecure-Requests":["1"]}},"common_log":"183.129.165.194 - - [18/Feb/2022:09:21:28 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000004523,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
issuer-admin_1      | {"level":"info","ts":1645176089.779112,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"183.129.165.194:45950","proto":"HTTP/1.1","method":"GET","host":"47.108.93.62:8081","uri":"/favicon.ico","headers":{"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"],"Accept":["image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"],"Referer":["http://47.108.93.62:8081/"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-CN,zh;q=0.9"],"Cookie":["io=IRzsWE1QPM3_bhCGAAAA"]}},"common_log":"183.129.165.194 - - [18/Feb/2022:09:21:29 +0000] \"GET /favicon.ico HTTP/1.1\" 0 0","user_id":"","duration":0.000004144,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}

So what to do next ？Thank you

**Comment by esune** [comment] 2022-02-18 17:03
If the webserver is responding (as it seems to be doing) I am honestly not sure, maybe some firewall/networking setting used to expose the services needs tweaking? The container appears to be working as expected.

**Comment by zhangbobo2023** [comment] 2022-02-22 10:01
@esune   the curl cmd logs as follow，the Content-Length is 0 ：

root@localhost:/home/ubuntu/issuer-kit/docker# curl 192.168.8.65:8082 -v
* Rebuilt URL to: 192.168.8.65:8082/
*   Trying 192.168.8.65...
* Connected to 192.168.8.65 (192.168.8.65) port 8082 (#0)
> GET / HTTP/1.1
> Host: 192.168.8.65:8082
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Tue, 22 Feb 2022 09:57:03 GMT
< Content-Length: 0
<
* Connection #0 to host 192.168.8.65 left intact

_and the terminal log ：_

issuer-web_1        | {"level":"info","ts":1645523823.1334841,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.8.65:45026","proto":"HTTP/1.1","method":"GET","host":"192.168.8.65:8082","uri":"/","headers":{"User-Agent":["curl/7.47.0"],"Accept":["*/*"]}},"common_log":"192.168.8.65 - - [22/Feb/2022:09:57:03 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000006362,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}

**Closed** 2022-02-24 02:01 UTC

**Comment by esune** [comment] 2022-02-24 16:27
@WhiteSeasons were you able to resolve the issue? Do you mind posting here the resolution in case someone else hits the same problem?

Unfortunately I wasn't able to reproduce the issue to troubleshoot and suggest a resolution.
